### ISSUE TITLE
Environment variables without `_texdoc` suffix don't work

### ISSUE THREAD

**Issue by wtsnjp** [TeX-Live/texdoc#10]
According to the user manual (p. 8), Texdoc should accept following environment variables: `PAGER`, `BROWSER`, `DVIVIEWER`, `PSVIEWER`, and `PDFVIEWER`.

![texdoc](https://user-images.githubusercontent.com/9448125/40784335-59ff5758-6520-11e8-9c0e-7df0183799c0.png)

However only `*_texdoc` form of those work at least in my environment.

Looking into the source code (`config.tlu`), the environment variables with the suffix are used directly (with the function `set_config_elt_from_vars()`), but others are somehow checked the validty.

```lua
-- set config from environment if available
function setup_config_from_env ()
    local function set_config_elt_from_vars(key, vars)
        for _, var in ipairs(vars) do
            local value = os.getenv(var)
            if value then
                set_config_element(key, value, {src='env', name=var})
            end
        end
    end
    local function set_config_elt_from_option_env(key, var)
        if (os.type == "windows") then return end
        local value = os.getenv(var)
        if value then
            for cmd in string.gmatch(value, '([^:]+)') do
                if is_in_path(cmd) then
                    set_config_element(key, cmd, {src='env', name=var})
                    -- don't test other commands if we have found one
                    break
                end
            end
        end
    end
    set_config_elt_from_vars('viewer_pdf',
      {"PDFVIEWER_texdoc", "TEXDOCVIEW_pdf", "TEXDOC_VIEWER_PDF"})
    set_config_elt_from_option_env('viewer_pdf', "PDFVIEWER")
    set_config_elt_from_vars('viewer_ps',
      {"PSVIEWER_texdoc", "TEXDOCVIEW_ps", "TEXDOC_VIEWER_PS"})
    set_config_elt_from_option_env('viewer_ps', "PSVIEWER")
    set_config_elt_from_vars('viewer_dvi',
      {"DVIVIEWER_texdoc", "TEXDOCVIEW_dvi", "TEXDOC_VIEWER_DVI"})
    set_config_elt_from_option_env('viewer_dvi', "DVIVIEWER")
    set_config_elt_from_vars('viewer_html',
      {"BROWSER_texdoc", "TEXDOCVIEW_html", "TEXDOC_VIEWER_HTML"})
    set_config_elt_from_option_env('viewer_html', "BROWSER")
    set_config_elt_from_vars('viewer_md',
      {"MDVIEWER_texdoc", "TEXDOCVIEW_md", "TEXDOC_VIEWER_MD"})
    set_config_elt_from_option_env('viewer_md', "PAGER")
    set_config_elt_from_vars('viewer_txt',
      {"PAGER_texdoc", "TEXDOCVIEW_txt", "TEXDOC_VIEWER_TXT"})
    set_config_elt_from_option_env('viewer_txt', "PAGER")
end
```

It seems this varification is not working well because even a valid value, e.g. on macOS:

```
$ export PDFVIEWER="open -a Preview.app"
```

doesn't work. Furthermore, the function `set_config_elt_from_option_env()` seems not supporting Windows, i.e. environment variables without the suffix are not supported for Windows (and this behavior is not documented!)

I think users are responsible for setting the valid exvironment variables, so we don't need to check any validity of their values. I'd like to abandon the function `set_config_elt_from_option_env()` and treat all environment variables by `set_config_elt_from_vars()` in order to fix this bug.

p.s. The help text was wrong for long time; it said the envrionment variables specially for Texdoc is `texdoc_*`, but it is actually `*_texdoc`. I already fixed this with the commit 17d2460f99c3ce413dcc09295319eff110affe9a.

**Comment by kberry** [comment]
I think users are responsible for setting the valid exvironment
    variables, so we don't need to check any validity of their values.

I agree. Thanks.

**Comment by norbusan** [comment]
Agreed, too, if the user sets some strange env var to shoot himself, let it be!
