### ISSUE TITLE
pkgname.pdf vs. pkgname-{foo,doc}.pdf

### ISSUE THREAD

**Issue by kberry** [TeX-Live/texdoc#105]
Hi Takuto - in the past, I've recommended that the main documentation
for a package be put in pkgname.pdf. And I recall also suggesting that
if tetexdoc is invoked as "texdoc pkgname", and there is a
"pkgname.pdf", that that be preferred. Which seems simple and desirable ...

.. but it's not uncommon for people to make pkgname.pdf be the typeset
code, and put manual in pkgname-doc.pdf or pkgname-manual.pdf or
probably other such names (not an easy thing to search for in tlpdb).

So my question is, if I change the recommendation to be
pkgname-{doc,manual}.pdf, can texdoc prefer that? Or (best case) maybe
it already does? Or should I continue to recommend pkgname.pdf and say
more about not using that filename for typeset code listings?

Preferring any foo-bar.pdf is definitely not desirable, since I see from a quick search in tlpdb that there are thousands of more or less "random" such PDFS, like foo-ex.pdf,
foo-{ru,fr,de,...}.pdf, etc...

Wdyt? --thanks, karl.

**Comment by wtsnjp** [comment]
> So my question is, if I change the recommendation to be pkgname-{doc,manual}.pdf, can texdoc prefer that? Or (best case) maybe it already does? Or should I continue to recommend pkgname.pdf and say more about not using that filename for typeset code listings?

To answer your question directly, changing or not changing the recommended document file name has little effect on Texdoc.

Already Texdoc prefers pkgname.pdf and pkgname-doc.pdf with -doc if both exist. This can be verified by running, for example, `texdoc frenchb`.

```shell
texdoc -lM -dscore frenchb
texdoc debug-version: /Users/takuto/Library/texmf/scripts/texdoc/texdoclib.tlu v4.0.1
texdoc debug-score: (e15e2e2) Start scoring /usr/local/texlive/2023/texmf-dist/doc/generic/babel-french/frenchb-doc.pdf
texdoc debug-score: (e15e2e2) Name used: generic/babel-french/frenchb-doc.pdf
texdoc debug-score: (e15e2e2) Start heuristic scoring with pattern: frenchb
texdoc debug-score: (e15e2e2) New heuristic score: 1.0. Reason: subword match
texdoc debug-score: (e15e2e2) New heuristic score: 4.5. Reason: exact match for derived pattern: frenchb-doc
texdoc debug-score: (e15e2e2) Final heuristic score: 4.5
texdoc debug-score: (e15e2e2) Max pattern score: 4.5
texdoc debug-score: (e15e2e2) Catalogue details bonus: +1.5
texdoc debug-score: (e15e2e2) Locale unmatch: -0.1
texdoc debug-score: (e15e2e2) Final score: 5.9
texdoc debug-score: (bacf5ba) Start scoring /usr/local/texlive/2023/texmf-dist/doc/generic/babel-french/frenchb.pdf
texdoc debug-score: (bacf5ba) Name used: generic/babel-french/frenchb.pdf
texdoc debug-score: (bacf5ba) Start heuristic scoring with pattern: frenchb
texdoc debug-score: (bacf5ba) New heuristic score: 4.0. Reason: exact match
texdoc debug-score: (bacf5ba) Final heuristic score: 4.0
texdoc debug-score: (bacf5ba) Max pattern score: 4.0
texdoc debug-score: (bacf5ba) Catalogue details bonus: +1.5
texdoc debug-score: (bacf5ba) Final score: 5.5
frenchb	5.9	/usr/local/texlive/2023/texmf-dist/doc/generic/babel-french/frenchb-doc.pdf	fr	User manual
frenchb	5.5	/usr/local/texlive/2023/texmf-dist/doc/generic/babel-french/frenchb.pdf		Package documentation
```

Precisely, if there is a `pkgname` with a suffix in the `suffix_list`, it is preferred over a simple `pkgname.pdf`. Of course, `pkgname.pdf` is often the top hit if one with suffixes does not exist.

https://github.com/TeX-Live/texdoc/blob/cdf5ca855dc652401cf591029564f7d5ce1b3ba8/texdoc.cnf#L88-L90

At the moment, this strategy is working well, and the situation where `pkgname.pdf` and `pkgname-{doc,manual}.pdf` are mixed in reality would not change even if the recommendation were changed. Therefore, I have no objection to the current proposal from a Texdoc technical point of view. Just to add for the record, I don't think it is desirable to have too many variations in the document suffixes that are not in the current `suffix_list`.

**Comment by kberry** [comment]
Thanks for all the info. I'm glad td already prefers foo-doc.pdf. Agreed no changes are needed for texdoc. Also agreed that adding yet more items to suffix_list would be undesirable. --best, karl.
