### ISSUE TITLE
texdoc 4.0.1 prefers geometry-de

### ISSUE THREAD

**Issue by kberry** [TeX-Live/texdoc#108]
texdoc geometry brings up geometry-de.pdf in preference to geometry.pdf. It didn't used to do this. Texdoc version 4.0.1 (2023-02-27).  All my locale variables are "C".  Thanks in advance ...

**Comment by wtsnjp** [comment]
I tried and it correctly selects `geometry.pdf` if the Texdoc `lang` config is set to `en`. Would you show me the debug output (with either `-D` or `-dconfig`)?

**Comment by wtsnjp** [comment]
I noticed this is completely identical to #104. Let us discuss this issue there.
