### ISSUE TITLE
texdoc metafun finds mycow.pdf

### ISSUE THREAD

**Issue by kberry** [TeX-Live/texdoc#109]
Texdoc 4.0.1 (2023-02-27) in current TL, texdoc -l metafun reports:
```
 1 texmf-dist/doc/context/sources/general/manuals/metafun/mycow.pdf             
 2 texmf-dist/doc/context/sources/general/manuals/metafun/somecow.pdf           
 3 texmf-dist/doc/context/documents/general/manuals/metafun-p.pdf               
 4 texmf-dist/doc/context/documents/general/manuals/metafun-s.pdf        
```

I guess the directory "metafun" is beating "metafun" as a substring in the filename. That's understandable, but nevertheless, the manuals are the -p.pdf (print size, a4) and -s.pdf (screen format, landscape orientation) files. Hans has used that convention in the past for other things, but I'm not seeing anything else currently in TL with those suffixes.

So maybe just a special case for metafun is the right thing.

**Comment by wtsnjp** [comment]
This is fixed by [f2fb792](https://github.com/TeX-Live/texdoc/commit/f2fb792397a375a2f287fc0ef6e49c11e7a5702e).
