### ISSUE TITLE
Suggestions about the environment variables

### ISSUE THREAD

**Issue by wtsnjp** [TeX-Live/texdoc#11]
Relate to #10, I have two suggestions about the environment variables.

## Abolishing old names

We are still supporting old names of environment variables such as `TEXDOCVIEW_txt` and `TEXDOC_VIEWER_TXT`. Do we really have to do this? I think the release of v3.0 is the good timing to abolish those.

cf. the user manual (again)

![texdoc](https://user-images.githubusercontent.com/9448125/40785538-ada0ca1a-6523-11e8-84fd-43c6ee116008.png)

## The order of priority: environment variables vs. texdoc.cnf

Currently, environment variables win over settings in texdoc.cnf (such as `viewer_txt`). I'm wondering this is truely desiable behavior, because envrionment variables like `PAGER` are commonly used.

So my suggestion for the order of priority is here:

1. Environment variables with the suffix (`*_texdoc`)
2. Settings in texdoc.cnf
3. Environment variables without the suffix
4. Built-in settings

What do you think?

**Comment by kberry** [comment]
We are still supporting old names of environment variables

They're just names. I dislike inflicting change on users unless there's
a strong reason, more than just removal of a couple of smallish lists
from the code.

    environment variables win over settings in texdoc.cnf

I think they should, yes.

    like `PAGER` are commonly used.

Which is precisely why it should win, it seems to me. If a user sets
PAGER (or whatever) in their env, it is desirable for that setting to
apply, by default, to anything that needs to page plain text. Otherwise
users would have to set a different envvar for every program, which
would clearly by awful.

If users want texdoc to use something different than other programs,
they can set the *_texdoc vars.

I personally appreciate that "cooperative" behavior of texdoc.

Thanks,
Karl

**Comment by norbusan** [comment]
I agree with Karl, if it is not too much disturbing code keeping the old names working would be nice. TeXies have a tendency to keep things as they set it up for generations ;-)

I didn't look into the code, but it would be nice if the OldName1/2 variables would be *first* used to set up the New Name variables with suffix (so `TEXDOCVIEW_txt` if set is used to define `PAGER_texdoc` etc, but only if `PAGER_texdoc` is not already defined).

After that your suggested order is nice. This way, old variable names will win over config file entries.

**Comment by wtsnjp** [comment]
Well, keeping the old name is not much painful. Okay, I will keep them.

What I don't like is the current documentation. Putting all names of environment variables including old ones equally looks like a bit complicated. I will sort them out (the old names will be moved to a footnote or elsewhere).

**Comment by norbusan** [comment]
Agreed, remove the old names from the documentation, or mention them only briefly in a comment or so. They should NOT be prominent!

**Comment by wtsnjp** [comment]
@kberry Since for an user who do *not* intentionally set

* `viewer_*` in texdoc.cnf, and
* the enveironment variables with the suffix `*_texdoc`

the environment variables without the suffix (e.g. `PAGER`) will work for them.

So, I think the order I suggested won't against your idea.
Thanks.

**Comment by kberry** [comment]
I think the old names should be in the manual somewhere. Agreed they
don't need to be anywhere near as prominent as the current manual makes
them. Thanks.

**Comment by wtsnjp** [comment]
It is a bit complicated to implement the priority first I suggested, so I'm going to change the order as follows:

1. Command line options, e.g. the `-c` options (cf. #7)
2. Settings in texdoc.cnf
3. Environment variables with the suffix (`*_texdoc`)
4. Environment variables without the suffix
5. Built-in settings

As a summary, from the original order, I want to swap the priorities of environment variables and settings in texdoc.cnf. Again, this is because texdoc.cnf is specific for Texdoc but environment variables are for general.

Please note that our default texdoc.cnf (i.e. `texdoc-dist.cnf`) doesn't set the viewers settings, so by default, Texdoc works cooperative (i.e. Texdoc is influenced by environment variables like `PAGER`)

**Comment by kberry** [comment]
sounds good to me. thanks.

**Comment by ilyaza** [comment]
This is completely backwards!  The purpose of environment variables is to allow having different behaviour in different concurrent sessions.  One should not override dynamic stuff (environment variables) by static stuff (content of files).

Moreover, some people (for example, I) would run TeXLive from a read-only media (a “mounted” ZIP file).  Then the environment variables are the primary way to configure the behaviour.

**Comment by wtsnjp** [comment]
I see your points. Indeed "dynamic stuff should win over static stuff" is true, but I also think "specific stuff (the config item, if specified) should win over general stuff (env variables without `_texdoc`)."

For now, please let me leave this issue opened for a while and see other responses. I won't make any change until we finish writing comprehensive test scripts anyway (see #31).

**Comment by wtsnjp** [comment]
After deep consideration, I decided to withdraw this suggestion. If you have any objection or another opinion, feel free to reopen this.
