### ISSUE TITLE
falling back to "source" files

### ISSUE THREAD

**Issue by kberry** [TeX-Live/texdoc#117]
Hi Takuto. Would you consider having texdoc fall back to looking in the source/ tree (kpathsea search type "source") if no good matches are found in doc?

In current TL (Texdoc 4.1 (2024-03-10), texdoc fontscripts doesn't find anything.  This is because I installed all files in the package in the source/ tree. It seemed more useful for users to keep everything together than to split off the pdf and README into doc. Since anyone actually considering using the package would want to see the source files. 

Over the years, I've done this for a few other packages in a similar situation (apl, bibtexperllibs, bibtools, hyphenex, metatype1). For some of these, texdoc finds files in another package; for others, it finds nothing.

Thanks for considering.

**Comment by wtsnjp** [comment]
Hi Karl, thanks for the suggestion. I think this is one of the nice future plans we have. To me this seems identical to #47.
