### ISSUE TITLE
The development page of our website

### ISSUE THREAD

**Issue by wtsnjp** [TeX-Live/texdoc#12]
@kberry since the README.md in this repostitory is already prepared, could you please make <https://www.tug.org/texdoc/dev/> a parmanent redirect to <https://github.com/TeX-Live/texdoc/>?

You don't have to hurry, but this is just for a reminder. Thanks.

**Comment by kberry** [comment]
Hi Takuto,

    since the README.md in this repostitory is already prepared

Right, thanks for noticing. I know I did that once before, but I uess it
got lost somehow. Anyway, I've made tug.org/texdoc/dev redirect.
.. to the README.md, as more doc-like, and it's easy to get to the tree
from anywhere. Thanks. -k

**Comment by wtsnjp** [comment]
Thank you!
