### ISSUE TITLE
The basic structure of Texdoc: the default texdoc.cnf and source code

### ISSUE THREAD

**Issue by wtsnjp** [TeX-Live/texdoc#15]
This is the topic from #13.

# The location of texdoc.cnf

Currently, the default texdoc.cnf (which placed at the top-level of this repository) is placed in `texmf-dist/texdoc/`. This is top-top-level of TeX Live, and the directory contains only texdoc.cnf; which is clearly unnecessary and undesirable.

One possible solution is putting the texdoc.cnf under `texmf-dist/scripts/texdoc/`, but in my opinion, it is still not ideal because:

* texdoc.cnf is not a script file (it should not treated exactly same as source code), and
* as a fact, there is no `*.cnf` file under `texmf-dist/scripts/`.

So, I'm looking for the best position of the file. If there are no other options, maybe we should put it under `texmf-dist/scripts/texdoc/`.

This change should be done at some point, but on the other hand, this can destroy the compatibility severely, so we should think twice before doing this change (how to do and when).

# Sould texdoclib require the modules by relative path?

The very rough scheme how Texdoc source works is:

1. `texdoc[.tlu]` setup the Kpathsea (kpse) and requrie `texdoc/main.tlu` using kpse
2. `texdoc/main.tlu` require `texdoc/texdoclib.tlu` using kpse
3. `texdoc/texdoclib.tlu` require other `texdoc/*.tlu` using kpse

I don't know and I can't understand why this program have such a complex scheme. Using kpse for requiring Texdoc's own source code is maybe not a good idea, because suppose some of the `*.tlu` is missing in a directory, the only missing files can be loaded somewhere completely different place in the system.

I'd like to change this to require the all files relatively (so loading files in the same directory) and remove the wrapper for `main.tlu` (abolish current `texdoc[.tlu]` and rename `main.tlu` to `texdoc[.tlu]`). This will make the scheme simpler and will prevent to load undesirable files (from somewhere using kpse). This won't change the installation method.

**Comment by kberry** [comment]
I see three different topics here. In reverse order:

3) I have no quarrel with finding the files relatively. Sounds like a
good idea. I also found the loading confusing (and problematic for
development).

2) scripts/texdoc is the simplest place for texdoc.cnf. I see no better
alternative. It doesn't have to do anything to compatibility, because
the code could certainly keep looking for <toplevel>/texdoc/texmf.cnf in
preference to <scriptdir>/texdoc.cnf. However, I also think this is not
necessary, because we are talking about our own default texdoc.cnf,
which people should not be modifying.

1) I still strongly request the prefixes. The issue is not texdoc
finding its own files, but some other package looking for "main.tlu" and
finding the wrong one.

In general, the deficiency in the TeX world that all filenames in the
runtime tree (tex files, scripts, fonts, everything but doc ...) have to
be globally unique, and not just package-unique, has been there since
day one, and will (so far as I can imagine) never be resolved. The
simplest and most reliable approach is just to put in the package name
as a prefix and be done with it. I agree it's annoying, and if I were
designing the system from scratch, I would do it differently.

I ask everyone who releases packages with unprefixed names anywhere in
the runtime to change, and don't think it would be right to make a
special case for texdoc. I just forgot to ask Manuel (because he updated
the program in TL himself).

Thanks,
Karl

**Comment by norbusan** [comment]
I can only underline point 1) of Karl, the uniqueness of files in the *whole* texmf trees is a pain, but we should try hard to enforce it.

**Comment by norbusan** [comment]
Yeah, that looks fine to me. I know it is not sophisticated, but please bare with us on that!

Concerning your two questions: Yes, we can change that without any problem, anything that does not involve changes to the binaries can easily be done.

Your second question I don't understand!

**Comment by wtsnjp** [comment]
When we got rid of Data.tlpdb.lua, I didn't know about the existence of distributions without the tlpdb.

I'm afraid similar things could happen this time; so some distributions may be put the file in other places, and will not make another plobrems? (just to make sure)

**Comment by wtsnjp** [comment]
4) What about the end-users' local configuration files. Currently, those are placed in `TEXMFHOME/texdoc` but should this also be changed to `TEXMFHOME/scripts/texdoc`? (I think this is better to be changed for coherence.)

**Comment by wtsnjp** [comment]
JFYR, the `--files` action is have to be fixed anyway (see #4), so if we're going to support both locations for user configuration, I will also enhance the action for this at the same time 👌

**Comment by kberry** [comment]
Takuto, if you haven't already done the work, let me withdraw my request
to move the location of texdoc.cnf. I hadn't thought about the user
directories. Now it seems like too much change for too little gain. Sorry. -k

**Comment by wtsnjp** [comment]
I got it. We won't change about the texdoc.cnf.

**Comment by wtsnjp** [comment]
The latest plan about the file structure of Texdoc is as follows:

```
TEXMF
├── texdoc
│   └── texdoc.cnf
└── scripts
    └── texdoc
        ├── texdoc.tlu
        ├── texdoclib.tlu
        ├── texdoclib-alias.tlu
        ├── texdoclib-config.tlu
        ├── texdoclib-constants.tlu
        ├── texdoclib-functions.tlu
        ├── texdoclib-score.tlu
        ├── texdoclib-search.tlu
        └── texdoclib-view.tlu
```

The file loading scheme of Texdoc is a bit complicated for some reasons, but let me explain that briefly. Currently, Texdoc works with following scheme:

1. The small wrapper (texdoc.tlu) loads the main.tlu using kpse
2. The main.tlu loads texdoclib.tlu using kpse
3. The texdoclib.tlu loads all other `*.tlu` files using kpse
4. Executing remaining part of main.tlu

I will modify this to:

1. The main program (texdoc.tlu) loads the **texdoclib.tlu** using kpse
2. The texdoclib.tlu loads all `texdoclib-*.tlu` **in the same directory** (loads by relative path)
3. The main program executes **the texdoclib.main() function** (which will be implemented in texdoclib.tlu itself or maybe in texdoclib-main.tlu; the location is not so essential anyway)

Since this will require modification on the first executable file (texdoc.tlu), the installation method for the development version in the README.md (symlinking `$TEXMFHOME/scripts/texdoc` to `$TEXDOC/script`) won't work **temporary** becase people have to replace `$TEXMFDIST/scripts/texdoc/texdoc.tlu` (or whatever) as well. (**Note that after releasing the new version of Texdoc, the installation method should work fine**.)

I don't know how many people will be infuluenced by this temporary problem (maybe only our three) but I don't want to keep such situation for the long time, so this change will be applied right before releasing Texdoc 3.1. In other words, if I apply this change, I will release Texdoc 3.1 imediately after that.

But before that, I will work on other opening issues.

Thanks,
Takuto

**Comment by kberry** [comment]
sounds fine to me. anyone working with the development texdoc can no doubt take care of themselves. i myself have never figured out a decent way to run a development texdoc. (My ideal would be to run from the source checkout with no further ado, but that has seemingly never been possible.)

**Comment by wtsnjp** [comment]
Finally, I've done my homework. As I claimed in the previous comment, I'd like to release Texdoc 3.1 soon enough (around the end of this March). I will appreciate if anyone test the latest code because this modification is relatively large.

**Comment by norbusan** [comment]
What about doing it into TeX Live now that we are in pre-release testing. You would get lots of tests and can easily fix problems before the release of TL!

**Comment by wtsnjp** [comment]
Hi Norbert, thanks for that suggestion. How exactly can I do that? Is just uploading to CTAN enough?

**Comment by norbusan** [comment]
Yes
