### ISSUE TITLE
The way to find documentation outside TeX Live

### ISSUE THREAD

**Issue by wtsnjp** [TeX-Live/texdoc#17]
I didn't know but Texdoc has a way to find documentation outside TeX Live.

![Section 2.1, Texdoc manual](https://user-images.githubusercontent.com/9448125/41518174-b02de9a8-72fb-11e8-8e93-1dd36c363d38.png)

Here, the first source provides a way to access the documentation.

However, this feature is not perfect.

### 1. Low efficiency (maybe because this feature is too minor?)

It seems this works without caching, so if there are huge trees under TEXDOCS, that will directly be a cause to slow down the performance of Texdoc. At this moment, I don't know anyone complaining about this, so maybe this is not a big problem.

### 2. No way to add extra information

It is impossible to add extra information (other from document files' name and their containing directory names). This can be solved by the new feature which is currently being discussed in #16.

### 3. Lack of documentation

The Texdoc manual mentions "the kpathsea variable TEXDOCS". This value is of course also be influenced by the envrionment variable TEXDOCS. On the other hand, this fact is not mentioned in Section ENVIRONMENTS of the manpage of Texdoc. We should fix this.

### 4. Is this enough?

I don't know how many programs are using the value of TEXDOCS, but is this can be easily customized by users just for Texdoc? If not, perhaps we should provide another way to add a searching souce tree.

**Comment by norbusan** [comment]
Interesting, I just checked on my system and I get
```
$ kpsewhich -var-value TEXDOCS
{{}/home/norbert/.texlive2018/texmf-config,/home/norbert/.texlive2018/texmf-var,/home/norbert/texmf,!!/usr/local/share/texmf,!!/home/norbert/tl/2018/texmf-config,!!/home/norbert/tl/2018/texmf-var,!!/home/norbert/tl/2018/texmf-dist}/doc//
```
and indeed, files there are found based on the directory and/or file name:
```
$ texdoc -l lucimatx
 1 /usr/local/share/texmf/doc/latex/lucimatx/lucimatx.pdf
 2 /usr/local/share/texmf/doc/latex/lucimatx/EULA.txt
 3 /usr/local/share/texmf/doc/latex/lucimatx/EULAmacs.txt
Enter number of file to view, RET to view 1, anything else to skip: 
```
But tracing the texlua call it seems that only the ls-R files are loaded and not the actual tree traversed.

That is ok, somehow, but not very intelligent at the moment, since searchers are somehow either the basename of the file, or the last directory component (from my experiments).

**Comment by wtsnjp** [comment]
I mentioned the environment variable `TEXDOCS` in the man page (192dbb77fbaef0e98132c8a7cd6dd3b5dfac7de2) to fix the third point. Other points are long-term tasks, and I wrote some ideas in the [TODO](https://github.com/TeX-Live/texdoc/wiki/TODO).

I'm closing this issue for now, but feel free to reopen if you have any related idea or suggestion.
