### ISSUE TITLE
Checking the existence of file before trying to open it

### ISSUE THREAD

**Issue by wtsnjp** [TeX-Live/texdoc#18]
At least for the `--just-view` action, Texdoc should check the existence of the file before tying to open it.

Currenly, Texdoc passes the file path to a selected viewer without checking the validity, so if some problem appears, error messages of the viewer are shown to the users. This could be confusing in some situations. An example on macOS:

```
$ texdoc --just-view /dev/null
/dev/null is not a regular file (use -f to see it)
```

Here "/dev/null is not a regular file (use -f to see it)" is a message of the less command, so the mentioned "-f" option is that of less, not of Texdoc, which is quite misleading. I know this example is extremely weird, but similar cases can be happen with other inputs on other systems.

Anyway, we should check the validity of the path for `--just-view` action with no doubt.

My question is: **should we check the validity of the path even for other search actions as well?**

If the databases (tlpdb and other databases which may be added for #16) and the cache files are always correct, we don't have to do this. But in case those could contain incorrect (or not up-to-dated) paths, this could be a problem.

We can check the validity of a path just before trying to open it (or put it to the result list), and in case it is not valid, Texdoc will try to open the next candidate (or remove it from the list). I think this approach is the best way concering about the performance.

**Comment by kberry** [comment]
how would you decide whether a path is valid? "existence" is not good enough; /dev/null exists. "readable" is not enough either, as /dev/null is readable.

In general, I think the above behavior is fine. Especially when used to view an arbitrary file, it seems to me it is not texdoc's job to decide what is valid and what is not.

If users are confused, they can use -v and texdoc will tell them what is happening. Maybe confusion can only happen in cases where there is no sensible result anyway?

**Comment by wtsnjp** [comment]
I think I gave a bad example. What I meant by the example is only that "If Texdoc passes a path to other tools without somehow checking the validity, the error messages could be misleading." Since I can't find a good example on macOS, I showed an example of /dev/null, but it is not good at all. We don't have to support such a weird input.

I think only checking the existence is just fine. This can be done by a simple function:

```lua
function file_exists(path)
  local f = io.open(path)
  if f ~= nil then
    io.close(f)
    return true
  else
    return false
  end
end
```

It is useful when users input non-exist file for `--just-view` and when the database (tlpdb or else) is incorrect or not up-to-dated for some reasons. Note that Texdoc has the list mode (and its machine-readable variant), which we don't want to include non-exist files.

In addition to that, I have a plan to add a variant of `alias` which allows users to specify absolute path, and this checking will be also helpful for that.

Well, at this point above cases are unlikely to happen (except `--just-view`), so we can leave this for the point we'll add a way to add extra databases or the variant of alias. Anyway, I think this is an easy task and not harmful.

**Comment by kberry** [comment]
making such a check and then silently going on to the next result makes sense for normal use.

i think when a result is skipped it should be reported in the -verbose output, though. that will help us or others trying to debug behavior (why expected file xyz isn't showing up).

**Comment by wtsnjp** [comment]
In stead of using the hand-made function I wrote before, I decided to use `lfs.isfile()`.

I already applied the change for `--just-view` action and it works fine (f353008aa2a57e51e3ec13c4789a04b051d974b3).

For the ordinal "view" action, I also agreed on Karl's suggestion:

> making such a check and then silently going on to the next result makes sense for normal use.

So, I'm going to implement this function (will be a loop), but please be aware if all of the candidates are  not exist, Texdoc will raise the "not found" error (cf. #23). This is likely to be occured in some destributions which omit some packages but using texlive.tlpdb (or the pre-hashed cache file generated from it) as the database.

**Comment by wtsnjp** [comment]
How about the "list" mode (and its variants, e.g. the "machine" mode). Should we get rid of the lines of not existing files, or just leave them for the list? There''s other possible solutions like showing them with certain tag like "[NOT EXIST]".

```
$ texdoc -l gotoh
 1 /usr/local/texlive/2018/texmf-dist/doc/latex/gotoh/gotoh.pdf
   = Package documentation [NOT EXIST]
 2 /usr/local/texlive/2018/texmf-dist/doc/latex/gotoh/README.md
   = Readme
Enter number of file to view, RET to view 1, anything else to skip:
```

What do you think the best?

**Comment by norbusan** [comment]
Not existing files should not be listed IMO

**Comment by kberry** [comment]
i agree -- nonexisting files should not be listed at all.

i can imagine that in a debugging mode they are reported as "tried but not found" -- but only for debugging, not for normal output.

i'm not sure if this is still in question, but fwiw, i still think for just-view, no checks should be made. it should just pass the file given to the appropriate viewer. that is what the user asked for.

**Comment by wtsnjp** [comment]
Since you both agreed not to put nonexisting files to the list, we will go that way.

Currently, Texdoc checks the existence of file just before trying to open it (in `view_file()` function). However, calculating scores for nonexisting files is time wasting, so now I'm thinking to treat this in the scoring scheme: if a file does not exist, the file will be get the lowest score immediately (this will naturally be reported to debug-score messages). This leads the nonexisting file won't be tried to viewed nor shown in the list.

For the --just-view behavior, IMO, what users are expecting is execute the exact behavior of the `view_file()` function. After applying the above change, no checks will be made before passing the appropriate viewer command and it might just failed with the command (i.e. the exact behavior Karl suggesting).
