### ISSUE TITLE
Separate markdown viewer from text viewer

### ISSUE THREAD

**Issue by wtsnjp** [TeX-Live/texdoc#19]
Currently, Texdoc opens markdown files (`*.md`) with a text viewer, which set by the environment variables `PAGER`, `PAGER_texdoc`, or the configuration item `viewer_txt`.

Since markdown become very popular format for software documentation and many tools to treat them have been develop, let's separate the viewer for markdown from general text viewer.

I'm going to add:

* New environment variables `MDVIEWER` and `MDVIEWER_texdoc`
* A new configuration item `viewer_md`

**Comment by wtsnjp** [comment]
Wait, `viewer_md` already exists but just undocumented. I will fix this.

**Comment by norbusan** [comment]
Wanted to say that ... there is already a setting for it, but viewers for md files are not very widely available, the biggest problem.

**Comment by wtsnjp** [comment]
I don't think that's a big problem for us (maybe a big problem for markdown lovers :stuck_out_tongue_winking_eye:).

We can just leave the **default** setting for `viewer_md` same as the general text viewer. We will lose nothing by allowing users to customize it.
