### ISSUE TITLE
get rid of Data.tlpdb.lua

### ISSUE THREAD

**Issue by kberry** [TeX-Live/texdoc#2]
I think it would be better to get rid of the Data.tlpdb.lua file. It is perpetually stale. And if it's only a backup. if texlive.tlpdb can't be found, IMHO it is better for texdoc to simply fail.

Takuto, if you agree, can you eradicate all traces of that file from the sources+docs? Thanks.

**Comment by wtsnjp** [comment]
Agreed. I'll do that.
