### ISSUE TITLE
search.tlu: assertion failed

### ISSUE THREAD

**Issue by thegreyshadow** [TeX-Live/texdoc#20]
Using Slackware64-current, TeXLive 2018. Package supplied by the distributor.
systemwide lua version: lua 5.1.5

invoking texdoc from the command line fails with the following message:
```
[eduardo:/run/media/eduardo/TI10701100D/musica]$ texdoc cjhebrew
[string "/usr/share/texmf-dist/scripts/texdoc/search.t..."]:569: assertion failed!
[eduardo:/run/media/eduardo/TI10701100D/musica]$ 
```

The error message refers to the search.tlu script.

Any help would be appreciated. Thanks in advance.

**Comment by wtsnjp** [comment]
It seems that the problem occurs because the `texlive.tlpdb` does not exist in your environment.

I have two questions to you:

1. How did you exactly install TeX Live 2018?
2. Could you please give us the output with `texdoc --debug cjhebrew`?

**Comment by thegreyshadow** [comment]
Thank you Takuto for answering.

On your questions:
1. I installed TeXlive from a package supplied by the distribution. This is a "base" package. To this I added two more packages, identified as "texlive-extra" and "texlive-docs".

The sources for these packages are the following:
Texlive-base: https://mirrors.slackware.com/slackware/slackware-current/source/t/texlive/

Texlive-extra:
Build script: https://slackware.nl/slackbuilds.org/14.2/office/texlive-extra/
Source: http://slackware.schoepfer.info/slackbuilds/texlive/2018/texlive-extra/texlive-extra-2018.180630.tar.xz

Texlive-docs:
Build script: https://slackware.nl/slackbuilds.org/14.2/office/texlive-docs/
http://slackware.schoepfer.info/slackbuilds/texlive/2018/texlive-docs/texlive-docs-2018.180630.tar.xz

These are basically all of TeXLive with all Windows-specific packages and software removed.

2. This is the output of ``texdoc --debug cjhebrew``:

```
[eduardo:/run/media/eduardo/TI10701100D/musica]$ texdoc --debug cjhebrew
texdoc debug-version: /usr/share/texmf-dist/scripts/texdoc/texdoclib.tlu version 3.0
texdoc debug-config: Setting 'debug_list=all' from command line option "--debug".
texdoc debug-config: Setting 'suffix_list=doc, -doc, _doc, .doc, /doc, manual, /manual, -manual, userguide, /user_guide, -guide, -user, -man, notes, -info, ref' in file "/usr/share/texmf-dist/texdoc/texdoc.cnf" on line 95.
texdoc debug-config: Setting 'lastfile_switch=true' in file "/usr/share/texmf-dist/texdoc/texdoc.cnf" on line 509.
texdoc debug-config: Setting 'lang=en' from operating system locale.
texdoc debug-config: Setting 'verbosity_level=2' from built-in defaults.
texdoc debug-config: Setting 'basename_list=readme, 00readme' from built-in defaults.
texdoc debug-config: Setting 'mode=view' from built-in defaults.
texdoc debug-config: Setting 'max_lines=20' from built-in defaults.
texdoc debug-config: Setting 'interact_switch=true' from built-in defaults.
texdoc debug-config: Setting 'fuzzy_level=5' from built-in defaults.
texdoc debug-config: Setting 'badbasename_list=readme, 00readme' from built-in defaults.
texdoc debug-config: Setting 'machine_switch=false' from built-in defaults.
texdoc debug-config: Setting 'ext_list=pdf, htm, html, txt, ps, dvi, ' from built-in defaults.
texdoc debug-config: Setting 'badext_list=txt, ' from built-in defaults.
texdoc debug-config: Setting 'rm_file=rm -f' from built-in defaults.
texdoc debug-config: Setting 'zipext_list=' from built-in defaults.
texdoc debug-config: Setting 'rm_dir=rmdir' from built-in defaults.
texdoc debug-files: Configuration files are:
texdoc debug-files: active      /usr/share/texmf-dist/texdoc/texdoc.cnf
texdoc debug-texdocs: texdocs[7] = /home/eduardo/.texlive2018/texmf-config/doc (index_mandatory=false, recursion_allowed=true)
texdoc debug-texdocs: texdocs[6] = /home/eduardo/.texlive2018/texmf-var/doc (index_mandatory=false, recursion_allowed=true)
texdoc debug-texdocs: texdocs[5] = /home/eduardo/texmf/doc (index_mandatory=false, recursion_allowed=true)
texdoc debug-texdocs: texdocs[4] = /usr/share/texmf-local/doc (index_mandatory=true, recursion_allowed=true)
texdoc debug-texdocs: texdocs[4] using index: /usr/share/texmf-local (shift=doc/)
texdoc debug-texdocs: texdocs[3] = /usr/share/texmf-config/doc (index_mandatory=true, recursion_allowed=true)
texdoc debug-texdocs: texdocs[2] = /usr/share/texmf-var/doc (index_mandatory=true, recursion_allowed=true)
texdoc debug-texdocs: texdocs[1] = /usr/share/texmf-dist/doc (index_mandatory=true, recursion_allowed=true)
texdoc debug-texdocs: texdocs[1] using index: /usr/share/texmf-dist (shift=doc/)
texdoc debug-tlpdb: Using shipped tlpdb data.
[string "/usr/share/texmf-dist/scripts/texdoc/search.t..."]:569: assertion failed!
[eduardo:/run/media/eduardo/TI10701100D/musica]$ 
```

Thanks again for your kindness.

**Comment by wtsnjp** [comment]
Thank you for reporting that.

Now, it is surely because of lacking `texlive.tlpdb`. Perhaps, the TeX Live from Slackware also removed the database. The destributor, if they want to activate Texdoc, have to include `texlive.tlpdb` or they should generate a pre-hashed cache file before releasing as we decided in #2.

Well, for you personally, I think there are two options to fix this problem for now:

#### 1. Installing TeX Live directly

I think this is the best solution for the time being. [The official page](https://tug.org/texlive/acquire-netinstall.html) will help you.

#### 2. Downloading texlive.tlpdb manually

This could be a bit troublesome, but downloading [texlive.tlpdb](http://tug.ctan.org/systems/texlive/tlnet/tlpkg/texlive.tlpdb) by yourself and put it to `/home/eduardo/.texlive2018/tlpkg/texlive.tlpdb` will probably work.

**Comment by wtsnjp** [comment]
Hmm... maybe it have to be placed else where. Anyway, the second solution cannot be a fundamental solution, because you have to think about how to update the database.

> Will wait to see if my distribution can apply a fix; otherwise I will install texlive directly.

I think this is a good idea.

> I will report the results of my endeavor.

Yes please. Thank you in advance!

**Comment by thegreyshadow** [comment]
Hi Takuto, 

The TeXLive packager for my distribution kindly provided a fix.
The fix is available in this forum post:

https://www.linuxquestions.org/questions/slackware-14/texlive-texdoc-not-working-4175634089/#post5882128

This effectively fixes the issue. Texdoc works again now.
Thanks for all your help and support.

**Comment by thegreyshadow** [comment]
Closing as fixed. Thanks!
