### ISSUE TITLE
How about adding a new configuration item to specify custom texlive.tlpdb path?

### ISSUE THREAD

**Issue by wtsnjp** [TeX-Live/texdoc#21]
Considering about the discussions in #20 and the [TeX Live mailing list](https://tug.org/pipermail/tex-live/2018-July/042083.html), adding a new configuration item to specify a custom path for texlive.tlpdb came to my mind. A possible syntax:

```
tlpdb = /custom/path/texlive.tlpdb
```

I don't think this have to be provided as a command line option, but providing as a configuration item sounds reasonable to me. After implementing the new `-c` option (#7), this hack can be easily used by the `rake gen_datafile` or whatever.

**Comment by kberry** [comment]
heartily agreed.

**Comment by norbusan** [comment]
I am currently building new Debian packages of TeX Live, the first ones including texdoc 3. I am having a hard time to incorporate automatic building of the cache, so for now I have pre-generated it by hand and added it to the Debian packaging as is.

This is not optimal, so I fully agree with any step making building of the cache more easy. I will try to play around with texdoc and see how I think this might be improved.
