### ISSUE TITLE
Fuzzy search does not work with aliases

### ISSUE THREAD

**Issue by e-kwsm** [TeX-Live/texdoc#30]
version: 16ddcb9

# Steps to Reproduce

```shellsession
$ texdoc -Ilcfuzzy_level=0 nonexistingpkg
Sorry, no documentation found for nonexistingpkg.
If you are unsure about the name, try searching CTAN's TeX catalogue at
https://ctan.org/search.html#byDescription.
$ mkdir -p $(kpsewhich -var-value=TEXMFHOME)/texdoc
$ echo 'alias nonexistingpkg = texdoc' >> $(kpsewhich -var-value=TEXMFHOME)/texdoc/texdoc.cnf
$ texdoc -Ilcfuzzy_level=0 nonexistingpkg
 1 /usr/local/texlive/2018/texmf-dist/doc/support/texdoc/texdoc.pdf
   = Package documentation
$ texdoc -Ilcfuzzy_level=1 nonexistingpkgs
Sorry, no documentation found for nonexistingpkgs.
If you are unsure about the name, try searching CTAN's TeX catalogue at
https://ctan.org/search.html#byDescription.
```

`$(kpsewhich -var-value=TEXMFHOME)/texdoc/texdoc.cnf` is read but fuzzy search returns `listings`, whose Levenshtein distance is 8.

**Comment by wtsnjp** [comment]
It's a specification at this point. I will work on that in the future but maybe not so soon (after v3.1).

**Comment by e-kwsm** [comment]
If this is a feature, please specify it in the document.

**Comment by wtsnjp** [comment]
Actually, it is *somehow* already documented in Section 2.1:

> In case Texdoc cannot find any documentation here, fuzzy search will find the closest *package name* to the <keyword> and reselect the files (see 2.6).

**Comment by wtsnjp** [comment]
I will update that next time I edit the document.

**Comment by wtsnjp** [comment]
Just like the discussion above, we won't fix the feature for now (it will possibly be changed in the future) but declare the specification more clear in the document before releasing v3.1.
