### ISSUE TITLE
 Environment variables without `_texdoc` suffix don't work (see #10)

### ISSUE THREAD

**Issue by ilyaza** [TeX-Live/texdoc#32]
The issue #10 is closed, so I comment here.

I’m of divided opinion about checking environment.  The fact that the code does not work now is, of course, in a need for a fix.  (I was hit by this too, on Windows.)

On the other hand, the `_texdoc`-less variables are **very** widely used by other applications — which may lead to a conflict about the semantic of these variables.  Moreover, since the easy workaround is provided (by `_texdoc` suffix), such conflicts would not be reported.

On the gripping hand, if such a conflict arises, this workaround still works….

**Summary**: removing the check may lead to things suddenly breaking (and TeXdoc stopping to work when these variables are set anew) **if** the conflicts mentioned above actually exist.

**Comment by wtsnjp** [comment]
I got that you have a concern about removing the validity check, but I'm not sure what exactly validity check you're suggesting us to implement...

Moreover, we don't tackle possible future issues, so if you don't have an actual problem now, please kindly forget about the concern. We will think the solution when the issue come along.
