### ISSUE TITLE
Where is the command of `texdoc`

### ISSUE THREAD

**Issue by aisight** [TeX-Live/texdoc#33]
``Command 'texdoc' not found, but can be installed with:
sudo apt install texlive-base
``

I'm using Ubuntu 18.04. 
The texlive has been installed as `http://tug.org/texlive/quickinstall.html` indicated.
``/usr/local/texlive/2018/bin/x86_64-linux`` has been added to the PATH. And, no `texdoc` in this folder.

So, where is it?

**Comment by norbusan** [comment]
Did you install *all* of TeX Live in the above way (quickinstall)? You need `collection-binextra` installed. Please do
```
tlmgr install collection-binextra
```
or if you don't need all of it, simply
```
tlmgr install texdoc
```

**Comment by aisight** [comment]
`apt install texlive` will get `texdoc` working fine.
