### ISSUE TITLE
texdoc cm -> cm.ps example

### ISSUE THREAD

**Issue by kberry** [TeX-Live/texdoc#36]
Hi Takuto - texdoc cm yields texmf-dist/doc/latex/epslatex-fr/cm.ps as the first result; this is just an example image from that manual, and is useless/meaningless.

Knuth's README is the only core documentation I can think of in TL about the cm fonts themselves: texmf-dist/doc/fonts/cm/README. This only shows up as result #5.

I think this is a candidate for a simple alias/special case. At least, I can't imagine any way to change the algorithms to prefer that README that wouldn't be likely to mess up other results. wdyt?

**Comment by wtsnjp** [comment]
The behavior reproduced in my environment too and I agreed your point. I added a little note in the [TODO](https://github.com/TeX-Live/texdoc/wiki/TODO)
