### ISSUE TITLE
--files only shows active files

### ISSUE THREAD

**Issue by kberry** [TeX-Live/texdoc#4]
current texdoc --files (-f) only reports active config files, it seems. 

Page 7 of the manual, the description of --files, says it reports all the config files, and reports whether they are "active, not found, or disabled". I think it would be nice to restore that behavior. I don't see another way to get texdoc to report all the config files it can use. wdyt?

**Comment by wtsnjp** [comment]
Actually, it seems that problem doesn't occur in my environment. Here's the output I got in my laptop (paths shown here are a little modified):

```
$ texdoc -f
~/lib/texmf/scripts/texdoc/texdoclib.tlu 3.0
Configuration files are:
    active	~/lib/texmf/texdoc/texdoc.cnf
    active	~/lib/texmf/texdoc/texdoc-dist.cnf
    disabled	/usr/local/texlive/2017/texmf-dist/texdoc/texdoc.cnf
Recommended file(s) for personal settings:
    ~/lib/texmf/texdoc/texdoc.cnf
```

**Comment by wtsnjp** [comment]
I had a look on the source code, but there's no process to omit disabled files. Technically, what the code do is:

1. Searching files which match following conditions:
    - Exists under the `$TEXMF/texdoc`
    - Having a name which is one of `texdoc-$SELFAUTOLOC.cnf`, `texdoc.cnf`, `texdoc-dist.cnf`
2. showing all of the found files with their status

So, I have no idea why this doesn't work well in your environment. I think I need more information about your situation.

**Comment by kberry** [comment]
for you, too, it is only reporting active or disabled cnf files. not the ones that are "not found". in fact, i do not see that string in the sources any more.

to repeat, the doc says that every directory in $TEXMF is a candidate. there should be a lot of "not found" texmf.cnf files as a result.

for example, in your case, /usr/local/texlive/texmf-local/texdoc/texdoc.cnf (from $TEXMFLOCAL) should be reported as "not found". and then there are all the -config and -var trees.

for me, i don't have a texdoc.cnf in $TEXMFHOME (/u/karl/texmf/texdoc/texdoc.cnf), so that too should be reported as "not found".

does that make sense? thanks.

**Comment by wtsnjp** [comment]
Ah, "not found" one. OK, I'll work on that.

**Comment by wtsnjp** [comment]
I fixed to show the "not found" config files. It seems to work fine and I agree in principle that this behavior is preferable.

However, I feel the output of the "files" action is a bit noisy (again, paths shown here are a little modified):

```
$ texdoc -f
/Users/asakura/Library/texmf/scripts/texdoc/texdoclib.tlu 3.0
Configuration files are:
    not found	/Users/asakura/Library/texlive/2018/texmf-var/texdoc/texdoc-x86_64-darwin.cnf
    not found	/Users/asakura/Library/texlive/2018/texmf-var/texdoc/texdoc.cnf
    not found	/Users/asakura/Library/texlive/2018/texmf-var/texdoc/texdoc-dist.cnf
    not found	/Users/asakura/Library/texmf/texdoc/texdoc-x86_64-darwin.cnf
    active	/Users/asakura/Library/texmf/texdoc/texdoc.cnf
    active	/Users/asakura/Library/texmf/texdoc/texdoc-dist.cnf
    not found	/usr/local/texlive/2018/texmf-dist/texdoc/texdoc-x86_64-darwin.cnf
    disabled	/usr/local/texlive/2018/texmf-dist/texdoc/texdoc.cnf
    not found	/usr/local/texlive/2018/texmf-dist/texdoc/texdoc-dist.cnf
Recommended file(s) for personal settings:
    /Users/asakura/Library/texmf/texdoc/texdoc.cnf
```

So, I would like to show "not found" files only if a user specifies the `-v` option. The debug output with `-d files` will always show all files (including "not found" ones) anyway.
