### ISSUE TITLE
-d crash

### ISSUE THREAD

**Issue by kberry** [TeX-Live/texdoc#45]
texdoc -d (regardless of other args) for me results in:

..live/pretest/texmf-dist/scripts/texdoc/texdoclib-cli.tlu:52: bad argument #1 to 'match' (string expected, got nil)

also, it is annoying that it truncates the filename, making it impossible to copy/paste, aside from ambiguity. is there a way to avoid that?

**Comment by wtsnjp** [comment]
What exact input results in the error? In my environment, the option `-d`, it works perfectly fine.

The option `-d` requires a debug category as an argument, e.g.,

```
$ texdoc -d score texdoc
```

or you can use `-D` without any argument to turn all items on:

```
$ texdoc -D texdoc
```

(Please see the manual for the details.)

**Comment by kberry** [comment]
yes, of course that exact input ("texdoc -d"). you say -d requires an argument. ok, so the question is evidently, what happens when that argument is not given (as I am not giving it). It should be an error message that says something like "-d requires an argument; try --help for more info", not a Lua-level error.
