### ISSUE TITLE
Get rid of old/unused stuff

### ISSUE THREAD

**Issue by wtsnjp** [TeX-Live/texdoc#5]
I'd like to remove following things (but not so soon):

* `TODO.md`: we can use [GitHub's issues (here)](https://github.com/TeX-Live/texdoc/issues) instead
* some in the `doc/`: I want to unify the build tool even for the documents
* all in `tools/`: I'm going to replace these by new scripts/tools
    * **scripts for testing**: we will use one of the sophisticated/well-known frameworks
    * **the gen-datafiles**: take into the scope of the build tool (I'm not sure about this)
    * any other necessary things? → **if there are, please comment that**

Some of the old scripts in this repository are unknown how to use; perhaps no one is using.

**Comment by wtsnjp** [comment]
All necessary operations (testing and generating the pre-hashed cache file) are implemented to Rakefile (and the equivalent Makefile by @norbusan; see #6), so I think now we can remove the tools dir. If there's no objection, I will do this soon. (Of course, we can revert it using git anytime if necessary)

**Comment by norbusan** [comment]
Fine with me

**Comment by wtsnjp** [comment]
All done; closing.
