### ISSUE TITLE
`sh: realpath: command not found`

### ISSUE THREAD

**Issue by samcarter** [TeX-Live/texdoc#52]
I just updated to Texdoc 3.2 (2020-02-02) and now I get 

```
sh: realpath: command not found
```

each time I use texdoc. Any ideas?

(operating system OS X 10.9)

Edit: OS X 10.15 seems to have the same problem, see https://tug.org/pipermail/tex-live/2020-February/044668.html

**Comment by wtsnjp** [comment]
Thanks for reporting. That problem comes from the code for #44 and should only occur on systems satisfying both of the following:

* a UNIX-like system
* a system without the `realpath` command

The workaround (da70247) should fix the problem.

**Comment by samcarter** [comment]
@wtsnjp Thanks a lot for fixing this so quickly! The code from the work branch seems to work fine.

**Comment by doraTeX** [comment]
@wtsnjp To support invoking `texdoc` with absolute paths on wider operating systems, how about using the following workaround?
This code intends to simulate `realpath` on a Unik-like system that has `bash` and `readlink`, including macOS.

```lua
local function realpath(p)
    if os.type == 'unix' then
        local e = os.execute('which realpath >/dev/null 2>&1')
        if e == 0 then
            local h = io.popen(string.format("realpath '%s'", p))
            local r = h:read('*a')
            h:close()
            return r:gsub('\n$', '')
        else
            e = os.execute('which bash >/dev/null 2>&1 && which readlink >/dev/null 2>&1')
            if e == 0 then
                local command = string.format('bash -c "TARGET=\\"%s\\"; if [[ -L \\"\\$TARGET\\" ]]; then REAL=\\$(readlink \\"\\$TARGET\\"); echo \\$(cd \\$(dirname \\"\\$TARGET\\")/\\$(dirname \\$REAL) && pwd)/\\$(basename \\$REAL); else echo \\$(cd \\$(dirname \\"\\$TARGET\\") && pwd)/\\$(basename \\"\\$TARGET\\"); fi"', p)
                local h = io.popen(command)
                local r = h:read('*a')
                h:close()
                return r:gsub('\n$', '')
            else
                return ''
            end
        end
    else
        return ''
    end
end
```

**Comment by wtsnjp** [comment]
@doraTeX thank you for the suggestion.

We concluded that supporting only systems with the `realpath` command is enough for this feature (cf. [#44](https://github.com/TeX-Live/texdoc/issues/44#issuecomment-568808061)). Meanwhile, on macOS, one who really wants to use this feature can install GNU coreutils, which contains the `realpath` command.
