### ISSUE TITLE
In re-packaged TL from MacPorts texdoc tries to find texlive.tlpdb

### ISSUE THREAD

**Issue by ballapete** [TeX-Live/texdoc#53]
In short: Running for example "texdoc verbatim" leads to "texdoc error: No texlive.tlpdb nor shipped tlpdb data found."

The issue is described here: https://trac.macports.org/ticket/58615

**Comment by wtsnjp** [comment]
That is a problem with the MacPorts packager, not ours. Please consult with the packager. Thanks.
