### ISSUE TITLE
texdoc siunitx displays synctex man page

### ISSUE THREAD

**Issue by nplatis** [TeX-Live/texdoc#56]
Just as the title says, `texdoc siunitx` displays the man page for `synctex`. That's on TeXLive 2020.

**Comment by e-kwsm** [comment]
I guess your machine misses siunitx and fuzzy search was performed.

It would be better if texdoc shows fuzzy search results similary to search engines like google:
```shellsession
$ texdoc texdac
Did you mean: "texdoc"
```

**Comment by wtsnjp** [comment]
@nplatis Does the package siunitx installed in your computer? Please try:

```
$ tlmgr info siunitx
```

**Comment by wtsnjp** [comment]
@e-kwsm Please read this thread first:

https://tug.org/pipermail/texdoc/2017q4/000415.html

Then after that, if you still have a suggestion, please open another issue.

**Comment by nplatis** [comment]
Sorry for opening the issue, you are right: `siunitx` is not installed (but I thought it was!).
