### ISSUE TITLE
Show Suggestion for Fuzzy Search

### ISSUE THREAD

**Issue by e-kwsm** [TeX-Live/texdoc#58]
At present texdoc performs fuzzy search by default, but shows nothing on it unless `-D` is specified, which is sometimes confusing.
Notably, if a query exactly matches a package that does not exist on a machine or that has no document, texdoc would pick different packages (https://github.com/TeX-Live/texdoc/issues/39#issuecomment-451638805, #56).

It would be better if texdoc shows a fuzzy search result similary to search engines like google:
```shellsession
$ texdoc texdac
Did you mean: "texdoc"
```

I don't think [a flag like `--fuzzy=interact`](https://tug.org/pipermail/texdoc/2017q4/000415.html) is necessary since we already have `-l`.

Also, the default Levenshtein distance of five is a bit large⁠—s**iunit**x and s**yncte**x are completely different (#56).

**Comment by wtsnjp** [comment]
I will wait for comments from @kberry before deciding the direction.

>  but shows nothing on it unless -D is specified

Technically speaking, this is not true. A message appears with `-v` as well.

```
$ texdoc -v texdac
texdoc info: Fuzzy search result: texdoc
```

> I don't think a flag like --fuzzy=interact is necessary since we already have -l.

I have two things to add here:

1. currently `-l` is nothing to do with fuzzy search
2. even if we will add a flag, I think it is better to add a new configuration item than a command-line option

**Comment by kberry** [comment]
I'm not sure I see the need for a cmdline or config file option.

Perhaps the line "texdoc info: Fuzzy search result: texdoc"
should be shown by default instead of requiring -v. (And omitted with -q of course.) That sounds useful to me. But I don't feel strongly about it.

**Comment by e-kwsm** [comment]
>> the default Levenshtein distance of five is a bit large
>
> Then what is your suggestion value? And why?

(Updated contents are not emailed)
I suggest two in consideration of swap: texd**co** vs texd**oc**.

**Comment by wtsnjp** [comment]
Then I will take 3 to allow a swap and one more.

For the other suggestion, let us see what will happen after fixing #55.
