### ISSUE TITLE
"DISPLAY is not set; your viewer will likely have problems" on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by michaelmhoffman** [TeX-Live/texdoc#59]
```
$ uname -a
Linux mhoffman-m02 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

$ texdoc texdoc
texdoc warning: DISPLAY is not set; your viewer will likely have problems.
texdoc warning: Try --list to list results instead of displaying them.
```

I am able to open the file just fine because this is on Windows Subsystem for Linux where the graphical user interface does not use X.

I suggest either (1) an exception to this warning for WSL like on Mac OS X, or (2) a configuration option that lets us switch this warning off specifically (rather than switching off all warnings).

**Comment by wtsnjp** [comment]
Thank you for reporting the problem.

> I am able to open the file just fine

How did you set up for this? Could you show me the result with the `-v` option? I tried WSL on my machine, and with the default configuration, it simply failed:

```
$ texdoc -v texdoc
texdoc warning: DISPLAY is not set; your viewer will likely have problems.
texdoc warning: Try --list to list results instead of displaying them.
texdoc info: View command: (see "/usr/local/texlive/2020/texmf-dist/doc/support/texdoc/texdoc.pdf")
texdoc info: Setting environment LC_CTYPE to: C.UTF-8
Error: no "view" mailcap rules found for type "application/pdf"
```

At this moment, Texdoc is not optimized for WSL. Before just removing the warnings, I would like to improve the feature to guess the viewer on WSL. What is the best way (i.e., the method which most likely to work under the default configuration) in WSL to open pdf files?

Then after that, if the way does not care about the `DISPLAY` variable, I will consider taking approach (1) to solve the issue.

**Comment by michaelmhoffman** [comment]
Thank you for your willingness to look into a complete solution for this!

It works for me because I have both the environment variable `BROWSER` and my mailcap set to use a script I have called `open` which essentially does this:

```bash
for file in "$@"; do
    file="$(wslpath -w "$(realpath "$file")")"
    powershell.exe -Command Start-Process "\"$file\""
done
```

So here are the results of `texdoc -v texdoc` in this configuration:

```
$ texdoc -v texdoc
texdoc warning: DISPLAY is not set; your viewer will likely have problems.
texdoc warning: Try --list to list results instead of displaying them.
texdoc info: View command: (xdg-open "/usr/share/texlive/texmf-dist/doc/support/texdoc/texdoc.pdf") &
texdoc info: Setting environment LC_CTYPE to: en_US.UTF-8
```

The call to wslpath and realpath convert `/usr/share/texlive/texmf-dist/doc/support/texdoc/texdoc.pdf"` to `\\wsl$\Ubuntu\usr\share\doc\texlive-doc\support\texdoc\texdoc.pdf`. 
`wslpath` is built into all but the oldest ("Legacy") versions of WSL. I believe it is necessary to use `realpath` because WSL symlinks are not necessarily understood by Windows applicatoins.

Using `powershell.exe -Command Start-Process` is the best way I have found to open something with the default Windows handler. `cmd.exe` seems appealing but has ancient quoting cruft once has to work around.

You can tell if you are in WSL with `uname -r`. If it contains `Microsoft` (title case) then we are running under WSL1, if it contains `microsoft` (lowercase), then you are running under WSL2.

**Comment by wtsnjp** [comment]
Thanks for your detailed answer. I was thinking to support WSL even with the viewer pop-up feature, but couldn't decide it because it seems to be a bit complicated than I first expected, and I didn't want to do too much for a single platform for the feature.

Recently I heard that [newer WSL2 will natively support GUI application](https://devblogs.microsoft.com/commandline/whats-new-in-the-windows-subsystem-for-linux-september-2020/#gui-apps). This might solve the problem without doing anything special on Texdoc-side. I will continue watching the changes in WSL and will see what happens with the GUI feature.

**Comment by michaelmhoffman** [comment]
Thank you for thinking about this. I think most WSL users will want to view PDFs in a native Windows viewer. I understand why you would not want to add a special case for WSL to use a native viewer yourself. But would you be willing to add an exception to this warning just like on Mac OS X, for people using native instead of X viewers there? Or a configuration option that lets us switch this warning off specifically (rather than switching off all warnings)?

**Comment by wtsnjp** [comment]
Ok. I will change the policy back to addressing only the warning message.

I would rather not want to judge WSL by calling an external command `uname`, so instead, I will just move the warning message to appear only if the viewer command invocation filed. This way, I think we don't need to make WSL an exception.
