### ISSUE TITLE
Using modern frameworks for testing and building

### ISSUE THREAD

**Issue by wtsnjp** [TeX-Live/texdoc#6]
To realize #5, I'm thinking to use frameworks common in the Ruby community. **I've not yet decided this, but I'll go for experiments.**

The motivations for this are:

* currently testing scripts make me difficult to add new test cases,
* some of the old scripts are unknown how to use & maybe not closs-platform, and
* unfortunately, I'm not good at Perl

## About testing

I'm doing experiments to use a framework [Aruba](https://github.com/cucumber/aruba) with [RSpec](https://qiita.com/luckypool/items/e3662170033347510c3c). This is ongoing in the [test branch](https://github.com/TeX-Live/texdoc/tree/test).

## About building

If the experiments for testing succeed, I'm going to do experiments with [Rake](https://github.com/ruby/rake) for building. I'd like to manage all of these operations with only a framework:

* installing/unistalling the develop version
* generating the pre-hashed pseudo cache file
* generating the documentation
* running help2man
* *anything else?*

And most importantly, the usages of new scripts/tools must be documented in the README.md.

**Comment by kberry** [comment]
I don't see what documentation generation (help2man and running tex) has
to do with a test framework. Straightforward Makefiles are what seems
simplest/best to me.

As for testing, if the tests need to parse tlpdb separately, as Norbert
says, using Perl means being able to use the TL modules to do that.
Reimplementing tlpdb parsing in another language does not seem appealing
to me.

But you are doing the work, so it's your decision :).

P.S. Totally agreed about tool documentation!

**Comment by wtsnjp** [comment]
I didn't say the documentation generation has to do with the test framework.

Please note that the first comment I made is talking about **two frameworks**: one for testing (RSpec) and one for building (Rake). The latter one, Rake, is Make-like program which can be written in ruby.

**Comment by wtsnjp** [comment]
And my idea about the documentation generation is: just above examples, it is nice to generate the documents, with just runnning

```
$ bundle exec rake doc
```

(THIS IS FUTURE WORK; NOT YET IMPREMENTED)

**Comment by norbusan** [comment]
Ouch, but why would I need rake or anything else to install? I just copy the files in the scripts dir to the texdoc folder in my TL installation for testing ... isn't that the easiest way?

But it is up to you, as said, I will surely not use rake or whatever for installing when copying files is enough ;-) :-D

**Comment by wtsnjp** [comment]
Well, if you don't want to install Rake or anything else, you can just go with the traditional style i.e. copy or symlink. Even in that case, the setups (the Gemfile and Rakefile) will do nothing bad with it. I will never ask you (and all Texdoc end-users) to install the frameworks, and I will never ask you to write or read ruby (in case something occur to me, please revert the perl scripts using git 🙇).

Firstly, like I said, writing tests without any framework is very painful for me. So, I decided to use a ruby framework ― RSpec. For this reason, it requires some ruby libraries anyway, so it is nothing to lose adding Rake (because all of them can be install with only a line: `bundle install`).

I am very happy to use Rake because:

* we can manage all tasks (installing, uninstalling, testing, generating documents, generating pre-hashed cache files, and so on) with only it,
* we can finish all of the tasks with only a line,
* the usage is extremely clear (I believe; anyway I can document all in the README),
* I'm pretty fluent in ruby (actually, it is my first programming language),
* easy to make it closs-platform (thanks to ruby and the dependencies),
* all of Bundler, RSpec, and Rake are very famous (mostly for young people), so I'm expecting using these frameworks will make it easier to invite other contributors.

### Additional note

If you don't want to install the dependencies into your system, but you want to try the new frameworks, please use

```
bundle install --path vendor/bundler
```

instead of `bundle install`. This will install the dependencies under `$TEXDOC/vendor`.

**Comment by wtsnjp** [comment]
I merged the "test" branch because the experiments have been done successfully. Writing tests are extremely important, and in fact, I found some bugs like #9.

I keep the tools dir for the time being, but we will remove it in the future.

I believe other important information are all wiritten in the README.md.

**Comment by norbusan** [comment]
Hi Takuto,
I took a look, and I was overwhelmed by the stuff needed for for rake. I understand your need for testing, here ruby framework might be a very good option, but for installation and building I prefer a Makefile. Here is a trivial one. I didn't convert the install/uninstall stuff, as I don't see the need for it, but sure enough I can do that, too. 
```

TEXDOC_VERSION=3.0
TEMP=/tmp

doc: doc/texdoc.pdf doc/texdoc.1

doc/texdoc.pdf: doc/texdoc.tex
        cd doc && latexmk -quiet texdoc.tex > /dev/null 2>&1

doc/texdoc.1: doc/texdoc.1.md
        cd doc && ronn -r --manual="Texdoc manual" --organization="Texdoc ${TEXDOC_VERSION}" texdoc.1.md 2>/dev/null

ctan: doc
        rm -rf ${TEMP}/texdoc-${TEXDOC_VERSION}/
        git archive --format=tar --prefix=texdoc-${TEXDOC_VERSION}/ HEAD | (cd ${TEMP} && tar xf -)
        # add generated pdf and man page
        cp doc/texdoc.pdf doc/texdoc.1 ${TEMP}/texdoc-${TEXDOC_VERSION}/doc
        cd ${TEMP}/texdoc-${TEXDOC_VERSION} && \
                rm -f .gitignore .travis.yml doc/.latexmkrc Gemfile Gemfile.lock Rakefile Makefile && \
                rm -rf spec tools
        cd ${TEMP} && zip -q -r texdoc-${TEXDOC_VERSION}.zip texdoc-${TEXDOC_VERSION}

clean:
        cd doc && latexmk -C -quiet
        -rm -f doc/texdoc.1

```

**Comment by wtsnjp** [comment]
Hmm... I can surely understand your point. Rake and other ruby frameworks are convenient but require tons of dependencies and kind of overkilling.

Because I also think like above, I hesitate to ask everyone to use rake. On the other hand, since the developers who will involve deeply with this repository are already need to use rspec (for testing) and ronn (for generating the manpage), I'm not sure adding rake is that a big problem.

**Comment by wtsnjp** [comment]
Well, I've just commited 3fe1c71e11573832be75e96ae1970680b5e3b29e to update the Rakefile and this will able to get rid of the `tools/gen-datafiles` (so `rake gen_datafile` will create the pre-hashed cache file). Just from curiosity: is this task also easily convert into Makefile?

**Comment by wtsnjp** [comment]
How about document about the Makefile in the Wiki.

Maybe writing `Makefile` into the `.gitignore` will be helpful?

**Comment by norbusan** [comment]
Concerning gen-datafiles, it is trivial translation of the Rakefile to shell:
```
texdoc_scriptdir=`pwd`/script
texdoc_cnf=`pwd`/texdoc.cnf
texdoc_tlu=$texdoc_scriptdir/texdoc.tlu

tmpdir=`mktemp -d`
texmf=$tmpdir/texmf

texmf_scripts=$texmf/scripts
texmf_texdoc=$texmf/texdoc
mkdir -p $texmf_scripts
mkdir -p $texmf_texdoc
ln -s $texdoc_scriptdir $texmf_scripts/texdoc
ln -s $texdoc_cnf $texmf_texdoc/texdoc.cnf

TEXMFHOME=$texmf
LC_ALL=C

export TEXMFHOME
export LC_ALL

texlua $texdoc_tlu -lM texlive-en >/dev/null

cache=`kpsewhich --var-value TEXMFVAR`/texdoc/cache-tlpdb.lua

echo cp $cache $texdoc_scriptdir/Data.tlpdb.lua

rm -rf $tmpdir
```
and of course this can be done in Makefile, or separate script.

Concerning Makefile: If you don't plan to include it, yeah, adding Makefile to the .gitignore is a good idea!

**Comment by norbusan** [comment]
BTW, isn't the shell code much easier to read than the Rake code? :-D

**Comment by wtsnjp** [comment]
That is simply because I wrote that very roughly with the mind of "done is better done perfect." 😅 
I'll refactor it anyway; maybe after releasing v3.0.

If you are ok with that, let's go that way 👍

**Comment by wtsnjp** [comment]
I refactored Rakefile and added `Makefile` to the `.gitignore`. All done and closing.
