### ISSUE TITLE
newcm -> newcomputermodern

### ISSUE THREAD

**Issue by kberry** [TeX-Live/texdoc#61]
I suggest making newcm an alias for newcomputermodern. Right now, texdoc newcm
brings up one of the doc files ("symbols"), which has newcm in the name, while texdoc newcomputermodern also lists the README and "sample" files. This is all as expected, but since newcm is so much easier to type and remember, an alias seems useful?

**Comment by wtsnjp** [comment]
Thank you for the suggestion. Aliases added.
