### ISSUE TITLE
[knuth-pdf] Incorrect startup file.

### ISSUE THREAD

**Issue by ascherer** [TeX-Live/texdoc#64]
* **TeX Live 2021** (on Kubuntu 20.04 LTS)
* **Texdoc 3.3 (2021-03-17)**
* Package **knuth-pdf** à la **revision 58470**

`texdoc knuth-pdf` opens `bibtex/bibtex-changes.pdf`, i.e., the first PDF file listed in `knuth-pdf.tlpobj`, instead of `index.pdf`, i.e., the top-most PDF in directory `knuth-pdf`. (Alternatively, there's also `index.html`.)

**Comment by wtsnjp** [comment]
Thanks for the report. I fixed the issue.

**Comment by ascherer** [comment]
I've created a local configuration file `~/.texlive2021/texmf/texdoc/texdoc.cnf` with a single line
```
alias knuth-pdf = knuth-pdf/index.pdf
```
after reading the introduction in the system-wide `texdoc.cnf`.  Works perfectly.  Thanks.
