### ISSUE TITLE
make `texdoc symbols` again open the comprehensive list of symbols

### ISSUE THREAD

**Issue by samcarter** [TeX-Live/texdoc#66]
Since a couple of months, `texdoc symbols` no longer brings up the comprehensive list of symbols `symbols-a4.pdf` but a document from unicode-math:

```
texdoc -l symbols
 1 /usr/local/texlive/2021/texmf-dist/doc/fonts/newcomputermodern/newcm-unimath-symbols.pdf
   = Math coverage and symbol comparison
 2 /usr/local/texlive/2021/texmf-dist/doc/latex/comprehensive/symbols-a4.pdf
   = The document (for A4 paper)
...
```

Would it be possible to do something to prioritise or alias the comprehensive list of symbols? This list is more general and many users are probably used to finding it via `texdoc symbols` (personally I typed this so often that it is pretty much automatic and this makes remembering to add `-a4` really hard)

My current workaround is 

```
alias symbols = symbols-a4.pdf
```

**Comment by wtsnjp** [comment]
Thanks for the report. I've added an alias.

**Comment by samcarter** [comment]
@wtsnjp Thanks a lot!
