### ISSUE TITLE
Data.tlpdb.lua is not reproducible

### ISSUE THREAD

**Issue by xworld21** [TeX-Live/texdoc#68]
When `texdoc` generates `cache-tlpdb.lua`, the order of the entries is not deterministic, and it changes on every run. This is essentially the same issue described in https://github.com/TeX-Live/texdoc/wiki/TODO#debug-outputs-reproducibility, but confined to `print_out_tlpdb`, and for packaging rather than debugging. Having a reproducible output would be helpful for packaging, if possible.

**Comment by wtsnjp** [comment]
Ok. Sorting debug output affects every Texdoc runs, but your suggestion affects only the runs generating the cache, which are slow anyway. It will not harm almost anything. I will work on this.

**Comment by xworld21** [comment]
Thanks!

If it helps, I just wrote a [small patch](https://github.com/xworld21/nixpkgs/blob/dc497c2c637b370968110bbc18a7d36af928a9b8/pkgs/tools/typesetting/tex/texlive/texdoc-reproducible-tlpdb-cache.patch) for myself to run some experiments. Not sure if it is good code, though. It's the first time I write in Lua.

**Comment by norbusan** [comment]
Looks fine to me! Thanks

**Comment by wtsnjp** [comment]
Oh, you already made a patch, thanks. Looks good to me as well.

Would you make a pull request so that we can see the CI results?
