### ISSUE TITLE
texdoc web -> tangle-changes.pdf?

### ISSUE THREAD

**Issue by kberry** [TeX-Live/texdoc#71]
The list returned from texdoc -I -l web (current tl, Texdoc 3.3.1 (2021-05-20)) starts like this:

````
 1 /home/texlive/karl/Master/texmf-dist/doc/generic/knuth-pdf/web/tangle-changes.pdf
 2 /home/texlive/karl/Master/texmf-dist/doc/generic/knuth-pdf/web/tangle.pdf    
 3 /home/texlive/karl/Master/texmf-dist/doc/generic/knuth-pdf/web/weave-changes.pdf
 4 /home/texlive/karl/Master/texmf-dist/doc/generic/knuth-pdf/web/weave.pdf     
 5 /home/texlive/karl/Master/texmf-dist/doc/generic/knuth-pdf/web/webman.pdf    
````

It would be better if webman.pdf was the first result. It seems strange that the tangle/weave[-changes] docs beat it in the heuristics ... --thanks, karl.

**Comment by wtsnjp** [comment]
I made a quick fix by adding a new alias as always.

But probably we should think about changing the calculation scheme for the heuristic score?

> It seems strange that the tangle/weave[-changes] docs beat it in the heuristics

They were actually didn't beat over the webman.pdf; all the five files under the `knuth-pdf/web` directory got the same score (of 2.5).

```
web	2.5	/usr/local/texlive/2021/texmf-dist/doc/generic/knuth-pdf/web/tangle-changes.pdf
web	2.5	/usr/local/texlive/2021/texmf-dist/doc/generic/knuth-pdf/web/tangle.pdf
web	2.5	/usr/local/texlive/2021/texmf-dist/doc/generic/knuth-pdf/web/weave-changes.pdf
web	2.5	/usr/local/texlive/2021/texmf-dist/doc/generic/knuth-pdf/web/weave.pdf
web	2.5	/usr/local/texlive/2021/texmf-dist/doc/generic/knuth-pdf/web/webman.pdf
```

Adding yet another small bonus for files that contain the exact query in the basename may be reasonable. Any thoughts?

**Comment by ballapete** [comment]
> Am 27.7.2021 um 00:48 schrieb kberry ***@***.***>:
> 
> It seems strange that the tangle/weave[-changes] docs beat it in the heuristics ...

The original sources did not change and so did their documentation. Then changes were applied. So it seems to me more logical to present the documentation about the applied changes first. The original documents are still the same – and possibly are well known…


Actually TANGLE and WEAVE documents are appendices to the WEB manual. They are extensions to what is written before, they are supposedly younger. It's natural, as in a CV, to present the more recent stuff first?

--
Greetings

  Pete

’Twas a woman who drove me to drink, and I never had the courtesy to thank her for it.
				— W.C. Fields

**Comment by kberry** [comment]
But probably we should think about changing the calculation scheme for the heuristic score?

I was surprised that "webman" did not match "web" better than the others
due to the Levenshtein stuff. Since there is an exact substring match,
seems like that should be worth something?

Or, in a more specific direction, I think there is already code that
knows about suffixes like "-manual", right? It would be good if just
plain "man" as a suffix (fooman.pdf) would have some benefit to the
score. I see about 20 such cases in TL.

Meanwhile, thanks for the alias. --best, karl.

**Comment by wtsnjp** [comment]
> I think there is already code that knows about suffixes like "-manual", right?

Ah, I'd clean forgotten about the `suffix_list`. Only `-man` was on the list. I've just added `man` also. With the new setup, the aliases for `NAMEman` are unnecessary, so I removed them. Thanks for reminding me about it.

**Comment by wtsnjp** [comment]
@ballapete Thanks for the following interesting idea.

> They are extensions to what is written before, they are supposedly younger. It's natural, as in a CV, to present the more recent stuff first?

I also think when the document is created can be useful. The only concern is, I'm afraid, there is no information on the creation date in the catalog. We can take the latest updated dates from the metadata of actual files, but we haven't taken such an approach in Texdoc. I'm not sure (1) the metadata is accurate or useful enough for this purpose, and (2) that can be efficiently done in the real-time calculation (I think point (2) is not that problematic though).

**Comment by kberry** [comment]
The mtime of the file in TL reflects when it was committed to TL. That is usually going to be close to the mtime of when it was created, and that in turn is usually going to be close to the mtime of when it was last modified. Usually, but not always, at each of those steps.

I think it would not be bad to use the mtime as an additional factor for the scoring, but I wouldn't give it much weight.

Parsing the pdf for the CreationDate or similar (pdfinfo foo.pdf | grep '^CreationDate:' | awk 'print {$2}') would probably be somewhat more useful, but that's an intensive operation. Maybe it could be done only when the top match is a tie? That might be interesting.

**Comment by wtsnjp** [comment]
> Parsing the pdf for the CreationDate or similar (pdfinfo foo.pdf | grep '^CreationDate:' | awk 'print {$2}') would probably be somewhat more useful, but that's an intensive operation. Maybe it could be done only when the top match is a tie? That might be interesting.

I think the pdfe library of LuaTeX would be useful for extracting the `CreationDate`. We can use the mtime for the fallback for the PDF files it failed to get that field of PDF metadata. Sounds like an interesting approach to me 👍
