### ISSUE TITLE
beamerarticle

### ISSUE THREAD

**Issue by samcarter** [TeX-Live/texdoc#74]
It would be nice if `texdoc beamerarticle` would bring up  beameruserguide.pdf instead of  `bsp-beamerarticle.pdf` (which belongs to an unrelated package).

Could maybe an alias be added?

**Comment by wtsnjp** [comment]
Thanks for the report. A patch from @muzimuzhi to fix this was merged.

**Comment by samcarter** [comment]
@muzimuzhi  & @wtsnjp  Thanks for fixing!
