### ISSUE TITLE
Show documentation without language code first when lang does not match any

### ISSUE THREAD

**Issue by wtsnjp** [TeX-Live/texdoc#78]
This is [reported by Denis](https://tug.org/pipermail/texdoc/2022q2/000534.html) in the mailing list.

> the locale of my computer is fr_FR.UTF-8. Nevertheless, here is the
> output of `texdoc -l etoc`:
> 
>  ┌────
>  │ 1 /home/bitouze/texlive/2022/texmf-dist/doc/latex/etoc/etoc-DE.pdf
>  │   = [de] Package documentation
>  │ 2 /home/bitouze/texlive/2022/texmf-dist/doc/latex/etoc/etoc.pdf
>  │   = Package documentation
>  │ 3 /home/bitouze/texlive/2022/texmf-dist/doc/latex/etoc/README.md
>  │   = Readme
>  └────
> 
> The German translation of the documentation shouldn't be the first one.

**Comment by jfbu** [comment]
I tried adding extra PDFs (as symlinks) in the doc/latex/etoc and running texhash but here is what I get:
```
$ texdoc -l etoc
 1 /usr/local/texlive/2022/texmf-dist/doc/latex/etoc/etoc-DE.pdf
   = [de] Package documentation (German)
 2 /usr/local/texlive/2022/texmf-dist/doc/latex/etoc/etoc.pdf
   = Package documentation (English)
 3 /usr/local/texlive/2022/texmf-dist/doc/latex/etoc/etoc-EN.pdf
 4 /usr/local/texlive/2022/texmf-dist/doc/latex/etoc/etoc-FR.pdf
 5 /usr/local/texlive/2022/texmf-dist/doc/latex/etoc/etoc-GB.pdf
 6 /usr/local/texlive/2022/texmf-dist/doc/latex/etoc/README.md
   = Readme
 7 /usr/local/texlive/2020/texmf-dist/doc/latex/etoc/etoc-DE.pdf
   = [de] Package documentation (German)
 8 /usr/local/texlive/2020/texmf-dist/doc/latex/etoc/etoc.pdf
   = Package documentation (English)
Enter number of file to view, RET to view 1, anything else to skip: X
```
still under 
```
$ locale
LANG="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL=
```

**Comment by ballapete** [comment]
> Am 1.8.2022 um 15:27 schrieb Jean-François B. ***@***.***>:
> 
> $ texdoc -l etoc
>  1 .../texmf-dist/doc/latex/etoc/etoc-DE.pdf
>    = [de] Package documentation (German)
>  2 .../texmf-dist/doc/latex/etoc/etoc.pdf
>    = Package documentation (English)
>  3 .../texmf-dist/doc/latex/etoc/etoc-EN.pdf
>  4 .../texmf-dist/doc/latex/etoc/etoc-FR.pdf
>  5 .../texmf-dist/doc/latex/etoc/etoc-GB.pdf
>  6 .../texmf-dist/doc/latex/etoc/README.md
>    = Readme
>  7 /usr/local/texlive/2020/texmf-dist/doc/latex/etoc/etoc-DE.pdf
>    = [de] Package documentation (German)
>  8 /usr/local/texlive/2020/texmf-dist/doc/latex/etoc/etoc.pdf
>    = Package documentation (English)
> Enter number of file to view, RET to view 1, anything else to skip: X

How comes that files from TL '20 are listed here?

The problem in your example is that obviously the file names are sorted in alphabetic order. Your sym-links are kind of neglected because they are not recorded in the TL DB file which contains information about the TeX Live packages. They are found, but they are no official documentation. So they are sorted at the end.

A simple solution would be to make the sorting routine prefer "GENERIC" file names over those with additional attributes. This would produce problems when the documentation is put into subdirectories or named in strange ways:

	.../texmf-dist/doc/latex/gzt/english/gzt-code.pdf
	.../texmf-dist/doc/latex/gzt/french/gzt-fr.pdf
	
	.../texmf-dist/doc/latex/eltex/pri_cz.pdf
	.../texmf-dist/doc/latex/eltex/man_en.pdf
	
	.../texmf-dist/doc/latex/changes/changes.english.withcode.pdf
	.../texmf-dist/doc/latex/changes/changes.english.pdf
	.../texmf-dist/doc/latex/changes/changes.ngerman.pdf
	
	.../texmf-dist/doc/latex/simples-matrices/simples-matrices-fra.pdf
	.../texmf-dist/doc/latex/simples-matrices/simples-matrices-eng.pdf
	.../texmf-dist/doc/latex/simples-matrices/simples-matrices.pdf
	
	.../texmf-dist/doc/latex/hagenberg-thesis/examples/HgbLabReportDE/main.pdf
	.../texmf-dist/doc/latex/hagenberg-thesis/examples/HgbLabReportEN/main.pdf
	.../texmf-dist/doc/latex/hagenberg-thesis/examples/HgbTermReport/main.pdf
	
	.../texmf-dist/doc/latex/pst-intersect/pst-intersect-DE.pdf
	.../texmf-dist/doc/latex/pst-intersect/pst-intersect.pdf
	
	.../texmf-dist/doc/latex/biblatex-dw/examples/en-authortitle-dw.pdf
	.../texmf-dist/doc/latex/biblatex-dw/examples/en-footnote-dw.pdf
	.../texmf-dist/doc/latex/biblatex-dw/examples/de-authortitle-dw.pdf
	.../texmf-dist/doc/latex/biblatex-dw/examples/de-footnote-dw.pdf
	.../texmf-dist/doc/latex/biblatex-dw/biblatex-dw.pdf
	.../texmf-dist/doc/latex/biblatex-dw/de-biblatex-dw.pdf
	
	.../texmf-dist/doc/latex/microtype/microtype.pdf
	.../texmf-dist/doc/latex/microtype/microtype-code.pdf
	.../texmf-dist/doc/latex/microtype-de/microtype-DE.pdf
	
	.../texmf-dist/doc/latex/polyglossia/polyglossia.pdf
	.../texmf-dist/doc/latex/polyglossia/example-korean.pdf
	.../texmf-dist/doc/latex/polyglossia/examples.pdf
	.../texmf-dist/doc/latex/polyglossia/example-thai.pdf
	.../texmf-dist/doc/latex/polyglossia/example-arabic.pdf
	
	.../texmf-dist/doc/latex/datetime/datetime.pdf
	.../texmf-dist/doc/latex/datetime/samples/dt-lang.pdf
	.../texmf-dist/doc/latex/datetime/samples/dt-sampl.pdf
	.../texmf-dist/doc/latex/datetime2-bahasai/datetime2-bahasai.pdf
	.../texmf-dist/doc/latex/datetime2-breton/datetime2-breton.pdf
	.../texmf-dist/doc/latex/datetime2-bulgarian/datetime2-bulgarian.pdf
	.../texmf-dist/doc/latex/datetime2-catalan/datetime2-catalan.pdf
	.../texmf-dist/doc/latex/datetime2-croatian/datetime2-croatian.pdf
	.../texmf-dist/doc/latex/datetime2-czech/datetime2-czech.pdf
	.../texmf-dist/doc/latex/datetime2-danish/datetime2-danish.pdf
	.../texmf-dist/doc/latex/datetime2-dutch/datetime2-dutch.pdf
	.../texmf-dist/doc/latex/datetime2-en-fulltext/datetime2-en-fulltext.pdf
	.../texmf-dist/doc/latex/datetime2-en-fulltext/sample-en-fulltext.pdf
	.../texmf-dist/doc/latex/datetime2-english/datetime2-english-sample.pdf
	.../texmf-dist/doc/latex/datetime2-english/datetime2-english.pdf
	.../texmf-dist/doc/latex/datetime2-esperanto/datetime2-esperanto.pdf
	.../texmf-dist/doc/latex/datetime2-estonian/datetime2-estonian.pdf
	.../texmf-dist/doc/latex/datetime2-finnish/datetime2-finnish.pdf
	.../texmf-dist/doc/latex/datetime2-french/datetime2-french-test-luatex.pdf
	.../texmf-dist/doc/latex/datetime2-french/datetime2-french-test-pdftex.pdf
	.../texmf-dist/doc/latex/datetime2-french/datetime2-french-test-xetex.pdf
	.../texmf-dist/doc/latex/datetime2-french/datetime2-french.pdf
	.../texmf-dist/doc/latex/datetime2-galician/datetime2-galician.pdf
	.../texmf-dist/doc/latex/datetime2-german/datetime2-german-doc.pdf
	.../texmf-dist/doc/latex/datetime2-greek/datetime2-greek.pdf
	.../texmf-dist/doc/latex/datetime2-hebrew/datetime2-hebrew.pdf
	.../texmf-dist/doc/latex/datetime2-icelandic/datetime2-icelandic.pdf
	.../texmf-dist/doc/latex/datetime2-irish/datetime2-irish.pdf
	.../texmf-dist/doc/latex/datetime2-it-fulltext/datetime2-it-fulltext.pdf
	.../texmf-dist/doc/latex/datetime2-latin/datetime2-latin.pdf
	.../texmf-dist/doc/latex/datetime2-lsorbian/datetime2-lsorbian.pdf
	.../texmf-dist/doc/latex/datetime2-magyar/datetime2-magyar.pdf
	.../texmf-dist/doc/latex/datetime2-norsk/datetime2-norsk.pdf
	.../texmf-dist/doc/latex/datetime2-polish/datetime2-polish.pdf
	.../texmf-dist/doc/latex/datetime2-portuges/datetime2-portuges.pdf
	.../texmf-dist/doc/latex/datetime2-romanian/datetime2-romanian-test-luatex.pdf
	.../texmf-dist/doc/latex/datetime2-romanian/datetime2-romanian-test-pdftex.pdf
	.../texmf-dist/doc/latex/datetime2-romanian/datetime2-romanian-test-xetex.pdf
	.../texmf-dist/doc/latex/datetime2-romanian/datetime2-romanian.pdf
	.../texmf-dist/doc/latex/datetime2-russian/datetime2-russian.pdf
	.../texmf-dist/doc/latex/datetime2-samin/datetime2-samin.pdf
	.../texmf-dist/doc/latex/datetime2-scottish/datetime2-scottish.pdf
	.../texmf-dist/doc/latex/datetime2-serbian/datetime2-serbian.pdf
	.../texmf-dist/doc/latex/datetime2-slovak/datetime2-slovak.pdf
	.../texmf-dist/doc/latex/datetime2-slovene/datetime2-slovene.pdf
	.../texmf-dist/doc/latex/datetime2-spanish/datetime2-spanish.pdf
	.../texmf-dist/doc/latex/datetime2-swedish/datetime2-swedish.pdf
	.../texmf-dist/doc/latex/datetime2-turkish/datetime2-turkish.pdf
	.../texmf-dist/doc/latex/datetime2-ukrainian/datetime2-ukrainian.pdf
	.../texmf-dist/doc/latex/datetime2-usorbian/datetime2-usorbian.pdf
	.../texmf-dist/doc/latex/datetime2-welsh/datetime2-welsh.pdf
	.../texmf-dist/doc/latex/datetime2/datetime2.pdf
	.../texmf-dist/doc/latex/datetime2/samples/datetime2-sample-babel.pdf
	.../texmf-dist/doc/latex/datetime2/samples/datetime2-sample-calc.pdf
	.../texmf-dist/doc/latex/datetime2/samples/datetime2-sample-filedate.pdf
	.../texmf-dist/doc/latex/datetime2/samples/datetime2-sample-hyperref.pdf
	.../texmf-dist/doc/latex/datetime2/samples/datetime2-sample-journal.pdf
	.../texmf-dist/doc/latex/datetime2/samples/datetime2-sample-styles.pdf
	.../texmf-dist/doc/latex/datetime2/samples/datetime2-sample-xe.pdf

Besides, I would prefer to see documentation in my LANG environment first. But what is actually the difference between pressing 1 or 8? Different hands and fingers involved?

--
Greetings

  Pete

When people run around and around in circles we say they are crazy. When planets do it we say they are orbiting.

**Comment by jfbu** [comment]
> How comes that files from TL '20 are listed here?

sorry I did not clean up. I use a special set-up with  a rolling TeXLive.  Most paths will appear with 2022 but some with 2020 but they are the same.

**Comment by jfbu** [comment]
> This is [reported by Denis](https://tug.org/pipermail/texdoc/2022q2/000534.html) in the mailing list.
> 
> > the locale of my computer is fr_FR.UTF-8. Nevertheless, here is the
> > output of `texdoc -l etoc`:

The hint at https://tug.org/pipermail/tex-live/2022-August/048359.html about adding ``lang = en`` to ``texdoc.cnf`` is only partially effective at my locale:

- it works for `colortbl`, `geometry`, ...
- it does not work for `etoc`

**Comment by wtsnjp** [comment]
The config `lang = en` makes sure Texdoc recognizes your locale is English.

English documents for colortbl and geometry have language code metadata, while that for etoc does not. Therefore, Texdoc cannot recognize that etoc.pdf is an English document.

These are different issues.
