### ISSUE TITLE
"Current settings" in the help is not accurate

### ISSUE THREAD

**Issue by wtsnjp** [TeX-Live/texdoc#9]
This bug is from ancient (at least exist from version 2.017; maybe more).

Texdoc later than version 0.70 (according to the [NEWS](https://github.com/TeX-Live/texdoc/blob/master/NEWS)) shows "current settings" in its help text.

With the default setups, when you specify only "-h":

```
$ texdoc -h
Usage: texdoc [OPTION]... NAME...
  or:  texdoc ACTION

Try to find appropriate TeX documentation for the specified NAME(s).
Alternatively, perform the given ACTION and exit.

Current settings: --view, --interact (default).
...
```

This is of course okay.

When you specify the "-l" option with "-h":

```
$ texdoc -h -l
Usage: texdoc [OPTION]... NAME...
  or:  texdoc ACTION

Try to find appropriate TeX documentation for the specified NAME(s).
Alternatively, perform the given ACTION and exit.

Current settings: --interact (default).
...
```

Here, the actual mode is "--list" but it doesn't appear. The same things can be said for other modes and nointeractive situations.

In the first place, I'm doubt that this function is really necessary. Current modes (and any other internal statuses) can be shown by the "--debug" option. Moreover, I think the help text must be extremely stable and should never failed to shown up, so I think it is better not to be generated dynamically.

If there aren't any objection, I will remove this function from v3.0.

**Comment by kberry** [comment]
what function are you referring to?

anyway, i certainly agree that the help message should show the standard defaults, not taking account of other options (which are ignored anyway, i believe).

i don't know what "current settings" were being reported -- maybe environment variable settings, etc.? anyway, i also think a more-or-less static help text is desirable.

**Comment by wtsnjp** [comment]
I meant the functionality to show the "current status". I'm going to delete the line in the help text.

It seems "current settings" aim to show the settings in user's `texdoc.cnf`. E.g. in case `mode = mixed` appear in your configure file, the help text will be like:

```
$ texdoc -h
Usage: texdoc [OPTION]... NAME...
  or:  texdoc ACTION

Try to find appropriate TeX documentation for the specified NAME(s).
Alternatively, perform the given ACTION and exit.

Current settings: --interact (default); --mixed (user config).
...
```

But even in those cases, the `--debug=config` option will show something like:

```
texdoc debug-config: Setting 'mode=mixed' in file "/path/to/your/texdoc.cnf" on line x
```

So, I think it is unnessesary to show the "current status" in the help text at all. (People who write their own settings in their config files are somehow be familiar with texdoc; they should know about the `--debug` option)

**Comment by wtsnjp** [comment]
And the standard default are already shown in the help text (see **(default)** in the list):

```
Options:
  -w, --view            Use view mode: start a viewer. (default)
  -m, --mixed           Use mixed mode (view or list).
  -l, --list            Use list mode: show a list of results.
  -s, --showall         Use showall mode: show also "bad" results.

  -i, --interact        Use interactive menus. (default)
  -I, --nointeract      Use plain lists, no interaction required.
  -M, --machine         Machine-readable output for lists (implies -I).

  -q, --quiet           Suppress warnings and most error messages.
  -v, --verbose         Print additional information (eg, viewer command).
  -D, --debug           Activate all debug output (equal to "--debug=all").
  -dLIST, --debug=LIST  Activate debug output restricted to LIST.
```
